import { StyleSheet } from "react-native";

export const colors = {
  text: "#0f172a",
  textSub: "#475569",
  muted: "#94a3b8",
  subtle: "#64748b",
  border: "#e2e8f0",
  inputBorder: "#cbd5e1",
  placeholder: "#9ca3af",
  background: "#f8fafc",
  surface: "#fff",
  surfaceAlt: "#f1f5f9",
  link: "#2563eb",
  danger: "#dc2626",
  dangerText: "#b91c1c",
  dangerBorder: "#fca5a5",
  success: "#059669",
  warning: "#d97706",
};

export const styles = StyleSheet.create({
  // --- レイアウト ---
  safe: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  scroll: { padding: 16, gap: 16 },
  headerWrap: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerUser: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerActions: { flexDirection: "row", gap: 8 },
  loginWrap: { flex: 1, justifyContent: "center", padding: 16 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  separator: { height: 1, backgroundColor: colors.border },
  fixedBottom: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },

  // --- テキスト ---
  h1: { fontSize: 24, fontWeight: "700", color: colors.text },
  h2: { flexShrink: 1, fontSize: 16, fontWeight: "600", color: colors.text },
  subtitle: { fontSize: 12, color: colors.subtle, marginTop: 2 },
  label: { fontSize: 13, color: colors.textSub, marginTop: 4 },
  muted: { fontSize: 13, color: colors.muted },
  link: { color: colors.link, fontSize: 13 },
  errorText: { fontSize: 13, color: colors.dangerText },

  // --- 入力 ---
  input: {
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  inputMultiline: { minHeight: 64, textAlignVertical: "top" },
  monoInput: { fontVariant: ["tabular-nums"], letterSpacing: 0.5 },
  amountInputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  amountPrefix: { fontSize: 14, color: colors.subtle },
  datePickerButton: {
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface,
  },
  datePickerText: { fontSize: 14, color: colors.text },
  datePickerPlaceholder: { fontSize: 14, color: colors.placeholder },
  datePickerClear: { fontSize: 18, color: colors.muted, paddingHorizontal: 4 },
  datePickerCompactRow: { flexDirection: "row", alignItems: "center", gap: 8 },

  // --- ボタン ---
  button: {
    backgroundColor: colors.text,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  buttonPressed: { opacity: 0.6 },
  buttonText: { color: "#fff", fontWeight: "600" },
  smallButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.surface,
  },
  smallButtonPressed: { opacity: 0.5 },
  smallButtonText: { fontSize: 13, color: colors.text },
  deleteButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    backgroundColor: colors.surface,
  },
  deleteButtonText: { fontSize: 13, color: colors.dangerText },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonText: { fontSize: 18, lineHeight: 20, color: colors.text },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 8,
  },

  // --- タブ / チップ ---
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabButtonActive: { borderBottomColor: colors.text },
  tabButtonPressed: { opacity: 0.5 },
  tabButtonText: { fontSize: 11, color: colors.subtle },
  tabButtonTextActive: { color: colors.text, fontWeight: "600" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.surface,
  },
  chipSelected: { backgroundColor: colors.text, borderColor: colors.text },
  chipText: { fontSize: 13, color: colors.textSub },
  chipTextSelected: { color: "#fff" },

  // --- ヘッダー / ログイン ---
  demoBadge: { backgroundColor: "#fef3c7", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2 },
  demoBadgeText: { fontSize: 11, fontWeight: "600", color: "#92400e" },
  loginError: {
    fontSize: 13,
    color: colors.dangerText,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  demoBox: { marginTop: 8, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12, gap: 6 },
  demoTitle: { fontSize: 11, color: colors.muted, textAlign: "center", marginBottom: 4 },
  demoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.background,
    borderRadius: 8,
  },
  demoLabel: { fontSize: 12, fontWeight: "600", color: colors.textSub },
  demoAccount: { fontSize: 12, color: colors.link },

  // --- 在庫一覧 ---
  sectionList: { gap: 12 },
  section: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    overflow: "hidden",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.surfaceAlt,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sectionHeaderNoBorder: { borderBottomWidth: 0 },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  sectionChevron: { fontSize: 10, color: colors.subtle },
  sectionTitle: { fontSize: 14, fontWeight: "600", color: colors.text },
  row: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    rowGap: 8,
    columnGap: 12,
  },
  rowLeft: { flexShrink: 1, flexGrow: 1, minWidth: 150 },
  rowRight: { flexShrink: 0, flexDirection: "row", alignItems: "center", gap: 8 },
  rowTitle: { fontSize: 15, fontWeight: "500", color: colors.text },
  rowTitleRow: { flexDirection: "row", alignItems: "center", gap: 4 },
  attrLine: { fontSize: 11, marginTop: 3, lineHeight: 14 },
  attrIcon: { color: colors.muted, letterSpacing: -1 },
  attrValue: { color: colors.textSub, fontVariant: ["tabular-nums"] },
  attrBadge: { color: "#374151", backgroundColor: "#f3f4f6" },
  attrMuted: { color: colors.muted, fontStyle: "italic" },
  avgAmountLine: { fontSize: 12, marginTop: 2, color: colors.success, fontVariant: ["tabular-nums"] },
  expiresAtLine: { fontSize: 12, marginTop: 2, fontVariant: ["tabular-nums"] },
  expiresAtSoon: { color: colors.warning },
  expiresAtExpired: { color: colors.danger },
  stock: {
    fontSize: 16,
    fontVariant: ["tabular-nums"],
    minWidth: 32,
    textAlign: "right",
    color: colors.text,
  },
  stockEmpty: { color: colors.danger },

  // --- 物品追加 ---
  barcodeNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: "#eff6ff",
    borderWidth: 1,
    borderColor: "#bfdbfe",
  },
  barcodeNoticeLabel: { fontSize: 11, color: "#1d4ed8", fontWeight: "600" },
  barcodeNoticeValue: { flex: 1, fontSize: 14, color: colors.text, fontVariant: ["tabular-nums"] },
  barcodeNoticeClear: { fontSize: 18, color: "#1d4ed8", paddingHorizontal: 4 },

  // --- マスタ管理 ---
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: 10,
    gap: 12,
  },
  listRowText: { flex: 1, fontSize: 14, color: colors.text },
  groupManageHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  groupManageTitle: { fontSize: 14, fontWeight: "600", color: colors.text },
  groupMembers: { paddingLeft: 4, gap: 2 },
  groupMemberText: { fontSize: 12, color: colors.subtle },
  groupMemberEmpty: { color: colors.danger },

  // --- ダイアログ ---
  modalFill: { flex: 1 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 16,
    gap: 12,
    maxHeight: "80%",
  },
  modalScroll: { flexShrink: 1 },
  modalContent: { gap: 12 },

  // --- 履歴 ---
  historyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  historyLeft: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  historyChange: { fontSize: 14, fontVariant: ["tabular-nums"], color: colors.text },
  historyAmount: { fontSize: 12, color: colors.success, fontVariant: ["tabular-nums"] },
  historyExpires: { fontSize: 11, color: colors.warning, marginTop: 2 },
  historyMeta: { alignItems: "flex-end" },
  historyUser: { fontSize: 11, color: colors.muted },

  // --- 分析 ---
  chartLabel: { position: "absolute", fontSize: 10, color: colors.subtle },
  legendRow: { flexDirection: "row", flexWrap: "wrap", columnGap: 12, rowGap: 4 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendSwatch: { width: 10, height: 10, borderRadius: 2 },
  legendText: { fontSize: 12, color: colors.textSub },

  // --- スキャナー ---
  scannerSafe: { flex: 1, backgroundColor: "#000" },
  scannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  scannerTitle: { color: "#fff", fontSize: 16, fontWeight: "600" },
  scannerTarget: { color: "#fde68a", fontSize: 12, marginTop: 2 },
  scannerClose: { color: "#93c5fd", fontSize: 14 },
  scannerBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    gap: 16,
  },
  cameraView: { ...StyleSheet.absoluteFill },
  scannerOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
  },
  scannerFrame: {
    width: 260,
    height: 160,
    borderWidth: 2,
    borderColor: "#22d3ee",
    borderRadius: 12,
  },
  scannerHint: {
    position: "absolute",
    bottom: 32,
    color: "#fff",
    fontSize: 13,
    textAlign: "center",
  },
});
