import { StyleSheet } from "react-native";

// メインカラーはティール (しおりカレンダーの緑と同系統)。意味ごとに success / warning / danger を使い分ける
export const colors = {
  primary: "#0d9488",
  primaryDark: "#0f766e",
  primarySoft: "#f0fdfa",
  primaryBorder: "#99f6e4",
  primaryText: "#115e59",
  text: "#0f172a",
  textSub: "#475569",
  muted: "#94a3b8",
  subtle: "#64748b",
  border: "#e2e8f0",
  inputBorder: "#cbd5e1",
  placeholder: "#9ca3af",
  background: "#f8fafc",
  surface: "#fff",
  surfaceAlt: "#f1f5f9",
  link: "#0d9488",
  danger: "#dc2626",
  dangerText: "#b91c1c",
  dangerBorder: "#fca5a5",
  dangerSoft: "#fef2f2",
  success: "#059669",
  successText: "#047857",
  successBorder: "#a7f3d0",
  successSoft: "#ecfdf5",
  warning: "#d97706",
  warningText: "#b45309",
  warningBorder: "#fde68a",
  warningSoft: "#fffbeb",
};

const softShadow = {
  shadowColor: "#0f172a",
  shadowOpacity: 0.05,
  shadowRadius: 6,
  shadowOffset: { width: 0, height: 2 },
  elevation: 1,
};

export const styles = StyleSheet.create({
  // --- レイアウト ---
  safe: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  scroll: { padding: 16, gap: 16 },
  headerWrap: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8 },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerUser: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerActions: { flexDirection: "row", gap: 8 },
  loginWrap: { flex: 1, justifyContent: "center", padding: 16 },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    ...softShadow,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  separator: { height: 1, backgroundColor: colors.border },
  fixedBottom: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },

  // --- テキスト ---
  h1: { fontSize: 20, fontWeight: "700", color: colors.text },
  h2: { flexShrink: 1, fontSize: 16, fontWeight: "600", color: colors.text },
  subtitle: { fontSize: 12, color: colors.subtle, marginTop: 2 },
  label: { fontSize: 13, fontWeight: "600", color: colors.textSub, marginTop: 4 },
  labelOptional: { fontSize: 11, fontWeight: "400", color: colors.muted },
  labelRequired: { fontSize: 11, fontWeight: "600", color: colors.danger },
  hint: { fontSize: 12, lineHeight: 17, color: colors.subtle },
  muted: { fontSize: 13, color: colors.muted },
  link: { color: colors.link, fontSize: 13 },
  errorText: { fontSize: 13, color: colors.dangerText },

  // --- 入力 ---
  input: {
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  inputMultiline: { minHeight: 64, textAlignVertical: "top" },
  monoInput: { fontVariant: ["tabular-nums"], letterSpacing: 0.5 },
  amountInputRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  amountPrefix: { fontSize: 14, color: colors.subtle },
  datePickerButton: {
    borderWidth: 1,
    borderColor: colors.inputBorder,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface,
  },
  datePickerText: { fontSize: 14, color: colors.text },
  datePickerPlaceholder: { fontSize: 14, color: colors.placeholder },
  datePickerClear: { fontSize: 18, color: colors.muted, paddingHorizontal: 4 },
  datePickerCompactRow: { flexDirection: "row", alignItems: "center", gap: 8 },

  // --- ボタン ---
  button: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
    alignItems: "center",
  },
  buttonPressed: { opacity: 0.6 },
  buttonText: { color: "#fff", fontWeight: "600" },
  smallButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.surface,
  },
  smallButtonPressed: { opacity: 0.5 },
  smallButtonText: { fontSize: 13, color: colors.text },
  deleteButton: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    backgroundColor: colors.surface,
  },
  deleteButtonText: { fontSize: 13, color: colors.dangerText },
  iconButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  iconButtonText: { fontSize: 18, lineHeight: 20, color: colors.text },
  iconButtonIncrement: { borderColor: colors.successBorder, backgroundColor: colors.successSoft },
  iconButtonIncrementText: { color: colors.successText, fontWeight: "700" },
  iconButtonDecrement: { borderColor: colors.warningBorder, backgroundColor: colors.warningSoft },
  iconButtonDecrementText: { color: colors.warningText, fontWeight: "700" },
  actions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    flexWrap: "wrap",
    gap: 8,
  },

  // --- タブ / チップ ---
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  tabButton: {
    flex: 1,
    paddingTop: 8,
    paddingBottom: 6,
    alignItems: "center",
    gap: 2,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabButtonActive: { borderBottomColor: colors.primary, backgroundColor: colors.primarySoft },
  tabButtonPressed: { opacity: 0.5 },
  tabButtonIcon: { fontSize: 18, lineHeight: 22, opacity: 0.55 },
  tabButtonIconActive: { opacity: 1 },
  tabButtonText: { fontSize: 10, color: colors.subtle },
  tabButtonTextActive: { color: colors.primaryText, fontWeight: "700" },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    backgroundColor: colors.surface,
  },
  chipSelected: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { fontSize: 13, color: colors.textSub },
  chipTextSelected: { color: "#fff" },

  // --- 画面の見出し / 説明 / 補足 ---
  intro: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  introIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  introIconText: { fontSize: 20 },
  introBody: { flex: 1, gap: 2 },
  introTitle: { fontSize: 18, fontWeight: "700", color: colors.text },
  introText: { fontSize: 13, lineHeight: 19, color: colors.subtle },
  callout: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  calloutIcon: { fontSize: 14, lineHeight: 19 },
  calloutText: { flex: 1, fontSize: 13, lineHeight: 19 },
  calloutInfo: { backgroundColor: colors.primarySoft, borderColor: colors.primaryBorder },
  calloutInfoText: { color: colors.primaryText },
  calloutSuccess: { backgroundColor: colors.successSoft, borderColor: colors.successBorder },
  calloutSuccessText: { color: colors.successText },
  calloutWarning: { backgroundColor: colors.warningSoft, borderColor: colors.warningBorder },
  calloutWarningText: { color: colors.warningText },
  calloutDanger: { backgroundColor: colors.dangerSoft, borderColor: "#fecaca" },
  calloutDangerText: { color: colors.dangerText },
  badge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2, alignSelf: "flex-start" },
  badgeText: { fontSize: 11, fontWeight: "600" },
  badgeNeutral: { backgroundColor: colors.surfaceAlt },
  badgeNeutralText: { color: colors.textSub },
  badgeInfo: { backgroundColor: "#ccfbf1" },
  badgeInfoText: { color: colors.primaryText },
  badgeSuccess: { backgroundColor: "#d1fae5" },
  badgeSuccessText: { color: colors.successText },
  badgeWarning: { backgroundColor: "#fef3c7" },
  badgeWarningText: { color: colors.warningText },
  badgeDanger: { backgroundColor: "#fee2e2" },
  badgeDangerText: { color: colors.dangerText },
  empty: { alignItems: "center", gap: 6, paddingVertical: 24, paddingHorizontal: 8 },
  emptyIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyIconText: { fontSize: 22 },
  emptyTitle: { fontSize: 14, fontWeight: "600", color: colors.text, textAlign: "center" },
  emptyText: { fontSize: 12, lineHeight: 18, color: colors.subtle, textAlign: "center" },
  colorDot: { width: 12, height: 12, borderRadius: 6 },
  legendInline: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 8 },
  legendInlineText: { fontSize: 11, color: colors.subtle },

  // --- ヘッダー / ログイン ---
  logo: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    ...softShadow,
  },
  logoLarge: { width: 56, height: 56, borderRadius: 17 },
  logoText: { fontSize: 20 },
  logoTextLarge: { fontSize: 30 },
  headerSub: { fontSize: 11, color: colors.subtle },
  loginHero: { alignItems: "center", gap: 8, marginBottom: 20 },
  loginTagline: { fontSize: 13, color: colors.subtle },
  demoBadge: { backgroundColor: "#fef3c7", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2 },
  demoBadgeText: { fontSize: 11, fontWeight: "600", color: "#92400e" },
  loginError: {
    fontSize: 13,
    color: colors.dangerText,
    backgroundColor: "#fef2f2",
    borderWidth: 1,
    borderColor: "#fecaca",
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },

  // --- 在庫一覧 ---
  sectionList: { gap: 12 },
  section: {
    borderWidth: 1,
    borderLeftWidth: 4,
    borderColor: colors.border,
    borderRadius: 10,
    overflow: "hidden",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sectionHeaderNoBorder: { borderBottomWidth: 0 },
  sectionTitleRow: { flexDirection: "row", alignItems: "center", gap: 8, flexShrink: 1 },
  sectionChevron: { fontSize: 10, color: colors.subtle },
  sectionTitle: { fontSize: 14, fontWeight: "600", color: colors.text },
  row: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    rowGap: 8,
    columnGap: 12,
  },
  rowLeft: { flexShrink: 1, flexGrow: 1, minWidth: 150 },
  rowRight: { flexShrink: 0, flexDirection: "row", alignItems: "center", gap: 8 },
  rowTitle: { fontSize: 15, fontWeight: "500", color: colors.text },
  rowTitleRow: { flexDirection: "row", alignItems: "center", flexWrap: "wrap", gap: 6 },
  attrLine: { fontSize: 11, marginTop: 3, lineHeight: 14 },
  attrIcon: { color: colors.muted, letterSpacing: -1 },
  attrValue: { color: colors.textSub, fontVariant: ["tabular-nums"] },
  attrBadge: { color: colors.textSub, backgroundColor: colors.surfaceAlt },
  attrMuted: { color: colors.muted, fontStyle: "italic" },
  avgAmountLine: { fontSize: 12, marginTop: 2, color: colors.success, fontVariant: ["tabular-nums"] },
  expiresAtLine: { fontSize: 12, marginTop: 2, fontVariant: ["tabular-nums"] },
  expiresAtSoon: { color: colors.warning },
  expiresAtExpired: { color: colors.danger },
  stock: {
    fontSize: 17,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
    minWidth: 32,
    textAlign: "right",
    color: colors.text,
  },
  stockEmpty: { color: colors.danger },

  // --- スキャン ---
  scanCard: { alignItems: "center", paddingVertical: 32, gap: 16 },
  scanHint: { fontSize: 13, color: colors.subtle, textAlign: "center" },
  scanButtonRing: { padding: 8, borderRadius: 88, backgroundColor: colors.primarySoft },
  scanButton: {
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    shadowColor: colors.primary,
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  stepRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  stepIcon: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center" },
  stepIconText: { fontSize: 17 },
  stepBody: { flex: 1, gap: 2 },
  stepTitle: { fontSize: 14, fontWeight: "600", color: colors.text },
  scanButtonIcon: { color: "#fff", fontSize: 44, lineHeight: 48 },
  scanButtonText: { color: "#fff", fontSize: 18, fontWeight: "600" },
  scanItemName: { fontSize: 16, fontWeight: "600", color: colors.text },
  scanBarcode: { fontSize: 12, color: colors.subtle, fontVariant: ["tabular-nums"] },
  scanItemBox: { backgroundColor: colors.surfaceAlt, borderRadius: 12, padding: 12, gap: 6 },
  scanChoiceRow: { flexDirection: "row", gap: 12 },
  scanChoice: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
    gap: 2,
  },
  scanChoiceIncrement: { backgroundColor: colors.success },
  scanChoiceDecrement: { backgroundColor: "#f59e0b" },
  scanChoiceDisabled: { opacity: 0.4 },
  scanChoiceIcon: { fontSize: 22, color: "#fff", fontWeight: "700" },
  scanChoiceText: { fontSize: 15, fontWeight: "700", color: "#fff" },

  // --- 物品追加 ---
  barcodeNotice: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
  },
  barcodeNoticeLabel: { fontSize: 11, color: colors.primaryText, fontWeight: "600" },
  barcodeNoticeValue: { flex: 1, fontSize: 14, color: colors.text, fontVariant: ["tabular-nums"] },
  barcodeNoticeClear: { fontSize: 18, color: colors.primaryText, paddingHorizontal: 4 },
  optionalBox: { backgroundColor: colors.surfaceAlt, borderRadius: 10, padding: 12, gap: 6 },

  // --- マスタ管理 ---
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: 10,
    gap: 12,
  },
  listRowText: { flex: 1, fontSize: 14, color: colors.text },
  groupManageHeader: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 4 },
  groupManageTitle: { fontSize: 14, fontWeight: "600", color: colors.text },
  groupMembers: { flexDirection: "row", flexWrap: "wrap", gap: 6, paddingLeft: 4 },

  // --- ダイアログ ---
  modalFill: { flex: 1 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.45)",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 16,
    gap: 12,
    maxHeight: "80%",
  },
  modalScroll: { flexShrink: 1 },
  modalContent: { gap: 12 },

  // --- 履歴 ---
  historyRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  historyLeft: { flexDirection: "row", alignItems: "flex-start", gap: 8 },
  historyChange: { fontSize: 14, fontWeight: "700", fontVariant: ["tabular-nums"], color: colors.text },
  historyChangeIn: { color: colors.successText },
  historyChangeOut: { color: colors.warningText },
  historyAmount: { fontSize: 12, color: colors.success, fontVariant: ["tabular-nums"] },
  historyExpires: { fontSize: 11, color: colors.warning, marginTop: 2 },
  historyMeta: { alignItems: "flex-end" },
  historyUser: { fontSize: 11, color: colors.muted },

  // --- 分析 ---
  chartLabel: { position: "absolute", fontSize: 10, color: colors.subtle },
  legendRow: { flexDirection: "row", flexWrap: "wrap", columnGap: 12, rowGap: 4 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendSwatch: { width: 10, height: 10, borderRadius: 2 },
  legendText: { fontSize: 12, color: colors.textSub },

  // --- スキャナー ---
  scannerSafe: { flex: 1, backgroundColor: "#000" },
  scannerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  scannerTitle: { color: "#fff", fontSize: 16, fontWeight: "600" },
  scannerTarget: { color: "#fde68a", fontSize: 12, marginTop: 2 },
  scannerClose: { color: "#93c5fd", fontSize: 14 },
  scannerBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    gap: 16,
  },
  cameraView: { ...StyleSheet.absoluteFill },
  scannerOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
  },
  scannerFrame: {
    width: 260,
    height: 160,
    borderWidth: 2,
    borderColor: "#5eead4",
    borderRadius: 12,
  },
  scannerHint: {
    position: "absolute",
    bottom: 32,
    color: "#fff",
    fontSize: 13,
    textAlign: "center",
  },
});
